// import file globals.css
import Link from "next/link";
// import './globals.css'
import "./globals.css";
import Image from "next/image";
// import fontawesome
import "@fortawesome/fontawesome-svg-core/styles.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Area Header */}
        <header>
          {/* Area Banner */}
          {/*<img src={"../images/logo.png"} alt="Logo Teknokrat"/>*/}
          <Image
            src={"/images/logo.png"}
            alt="Logo Teknokrat"
            width={320}
            height={60} priority
          ></Image>
          {/* Area Menu */}
          <nav className="mt-5 flex justify-center text-center">
            <Link
              href={"/"}
              className="bg-red-700 hover:bg-red-700 text-white rounded-full px-5 py-2.5 mr-2 w-52"
            >
              {" "}
              Data Mahasiswa{" "}
            </Link>
            <Link
              href={"/"}
              className="bg-red-700 hover:bg-red-700 text-white rounded-full px-5 py-2.5 ml-2 w-52"
            >
              {" "}
              Log Data Mahasiswa{" "}
            </Link>
          </nav>
        </header>

        {/* Area Content */}
        <section className="mt-5">{children}</section>

        {/* Area Footer */}
        <footer className="flex justify-center text-center bg-color1 text-color3-satu-a py-15px mt-5">
          Copyright &copy; 2024 - Bima Satya Nugraha
        </footer>
      </body>
    </html>
  );
}
